### ISSUE TITLE
Adding functionality to ManageUsersController.java

### ISSUE THREAD

**Issue by CelesteGiraffe** [Celeste-Artley/InventoryJavaOOP#5]
Currently working on Manage Users Controller to provide all the necessary functions in linking up with the databases.

**Comment by CelesteGiraffe** [comment]
Good job making progress by baking the current active-user (loggedInUser) visible here.

**Comment by JustinRFox** [comment]
The only issue currently remaining with this controller is the ability (or lack thereof, rather) to update a user's specific NON-Administrator user role.
